### ISSUE TITLE
Version mismatch between package.json and published npm release

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/ruby-semver#89]
npmjs has a `0.2.1` release at https://www.npmjs.com/package/@renovatebot/ruby-semver/v/0.2.1

But `ruby-semver`'s `package.json` still says:

https://github.com/renovatebot/ruby-semver/blob/88cc5da78937eab2e0a9f3e2c15092eaf419fc70/package.json#L1-L5

Probably should bump the version in `package.json` to `0.2.1`?

**Comment by rarkins** [comment]
I need to check the content if it matches

**Comment by rarkins** [comment]
[0.1.6 -> 0.2.0](https://app.renovatebot.com/package-diff?name=@renovatebot/ruby-semver&from=0.1.6&to=0.2.0)

[0.2.0 -> 0.2.1](https://app.renovatebot.com/package-diff?name=@renovatebot/ruby-semver&from=0.2.0&to=0.2.1)

For the last release there are a lot of changes but it looks like they could all be in the build

**Comment by rarkins** [comment]
Now published 1.0.0
